---
# tasks file for ansible-partition

- name: Import all vars from file
  include_vars:
    file: main.yml
- name: Create required users (if not exists)
  user:
    name: "{{ item.mount_point_user }}"
    shell: /sbin/nologin
    state: present
    append: true
  with_items:
    - "{{ partitions }}"
- name: Create required groups (if not exists)
  group:
    name: "{{ item.mount_point_group }}"
    state: present
  with_items:
    - "{{ partitions }}"
- name: Include ubuntu specific tasks
  include_tasks: "ubuntu.yml"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'