---
# Create and modify the partitions

- name: Verify there is the required disks available
  stat:
    path: "{{ item.device }}"
  with_items:
    - "{{ partitions }}"
- name: Unmount device (disks) for partitioning
  mount:
    path: "{{ item.device }}"
    state: unmounted
  with_items:
    - "{{ partitions }}"
- name: Create the partitions as defined
  parted:
      device:  "{{ item.device }}"
      number: "{{ item.number }}"
      part_start: "{{ item.part_start }}"
      part_end: "{{ item.part_end }}"
      part_type: primary
      label: gpt
      align: optimal
      state: present
  with_items:
    - "{{ partitions }}"
- name: Get new partition info
  parted:
    device: "{{ item }}"
    state: info
  register: part_info
  loop: "{{ unique_devices|list }}"
- name: (DEBUG) Show parted info resp
  debug:
    var: part_info
- name: Create a ext4 filesystem on partitions and check disk blocks
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item[0].disk.dev }}{{ item[1].part_index }}"
    opts: -cc
  loop: "{{ part_info.results|product(partitions)|list }}"
- name: Mount the created partitions
  ansible.posix.mount: 
    path: "{{ item[1].mount_point }}"
    src: "{{ item[0].disk.dev }}{{ item[1].part_index }}"
    fstype: ext4
    state: mounted
  loop: "{{ part_info.results|product(partitions)|list }}"
- name: Verify that file ownership and mode unchanged
  file:
    path: "{{ item.mount_point }}"
    owner: "{{ item.mount_point_user }}"
    group: "{{ item.mount_point_group }}"
    mode: "{{ item.mount_point_mode }}"
    state: directory
    recurse: true
  with_items:
    - "{{ partitions }}"
